author: The Great Rift Valley Software Company
author_url: https://riftvalleysoftware.com
hide_documentation_coverage: true

copyright: '© 2019 [The Great Rift Valley Software Company](https://riftvalleysoftware.com) under [open source license](https://github.com/RiftValleySoftware/RVS_GTDriver/blob/master/LICENSE).'

theme: fullwidth
